# Generated by Django 3.1.4 on 2020-12-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201209_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='option',
            new_name='delivery_option',
        ),
    ]
