# Generated by Django 3.1.4 on 2020-12-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201209_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='order_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
